
const accentColors={cyan:"#00dfe5",red:"#ff3728",purple:"#b931ff",orange:"#ff8a1f",green:"#50e88c",blue:"#388cff",gold:"#d3a24d",grey:"#6f6658"};
const beerLooks={gold:["#ffe985","#f3a217","#fff0d6"],amber:["#d64b1f","#5b160d","#e2af78"],stout:["#2b130e","#020101","#b87644"],redbeer:["#c4311f","#5b1008","#e2a270"],sour:["#ff98b5","#d84570","#fff0e2"],empty:["#222","#111","#ddd"]};
let state,activeTap,holdTimer;
async function loadState(){const saved=localStorage.getItem("booguels-final-pwa");if(saved){state=JSON.parse(saved)}else{const r=await fetch("beers.json?v=final2",{cache:"no-store"});state=await r.json()}render()}
function saveState(){localStorage.setItem("booguels-final-pwa",JSON.stringify(state))}
function tapCss(t){const a=accentColors[t.accent]||accentColors.grey;const b=beerLooks[t.beer||"gold"]||beerLooks.gold;return `--accent:${a};--beerTop:${b[0]};--beerBottom:${b[1]};--foam:${b[2]}`}
function renderTap(t){const empty=t.status!=="online";const extras=String(t.extras||"").split("\n").filter(Boolean).map(x=>`<div>${x}</div>`).join("");return `<section class="tap ${empty?"empty":"online"}" data-tap="${t.tap}" style="${tapCss(t)}"><div class="num">${t.tap}</div><div class="info"><div class="name">${empty?"EMPTY TAP":t.name}</div><div class="style">${empty?"COMING SOON":t.style}</div><div class="rule"></div><div class="stats"><div><div class="value">${empty?"-- %":t.abv+" %"}</div><div class="label">ABV</div></div><div><div class="value">${empty?"--":t.ibu}</div><div class="label">IBU</div></div></div></div><div class="extras">${empty?"":extras}</div><div class="glassWrap"><div class="pint"><div class="beer"></div><div class="foam"></div></div></div></section>`}
function render(){tapgrid.innerHTML=state.taps.sort((a,b)=>a.tap-b.tap).map(renderTap).join("");document.querySelectorAll(".tap").forEach(card=>{const n=+card.dataset.tap;card.addEventListener("touchstart",()=>{holdTimer=setTimeout(()=>openEditor(n),750)});card.addEventListener("touchend",()=>clearTimeout(holdTimer));card.addEventListener("mousedown",()=>{holdTimer=setTimeout(()=>openEditor(n),750)});card.addEventListener("mouseup",()=>clearTimeout(holdTimer));card.addEventListener("dblclick",()=>openEditor(n))})}
function openEditor(n){activeTap=state.taps.find(t=>t.tap===n);editorTitle.textContent="TAP "+n;status.value=activeTap.status||"online";name.value=activeTap.name||"";style.value=activeTap.style||"";abv.value=activeTap.abv||"";ibu.value=activeTap.ibu||"";extras.value=activeTap.extras||"";accent.value=activeTap.accent||"cyan";beer.value=activeTap.beer||"gold";editor.classList.remove("hidden")}
function close(){editor.classList.add("hidden")}
closeEditor.onclick=close;
emptyTap.onclick=()=>{if(!activeTap)return;Object.assign(activeTap,{status:"empty",name:"Empty Tap",style:"Coming Soon",abv:"",ibu:"",extras:"",accent:"grey",beer:"empty"});saveState();render();close()};
resetLocal.onclick=()=>{localStorage.removeItem("booguels-final-pwa");location.reload()};
saveTap.onclick=()=>{if(!activeTap)return;Object.assign(activeTap,{status:status.value,name:name.value,style:style.value,abv:abv.value,ibu:ibu.value,extras:extras.value,accent:accent.value,beer:beer.value});if(activeTap.status==="empty")Object.assign(activeTap,{name:"Empty Tap",style:"Coming Soon",abv:"",ibu:"",extras:"",accent:"grey",beer:"empty"});saveState();render();close()};
loadState();if("serviceWorker"in navigator){navigator.serviceWorker.register("./sw.js?v=final2").catch(()=>{})}
